### ISSUE TITLE
Mass_Centre_List & Modified DH Parameters

### ISSUE THREAD

**Issue by MarsGen2032** [bhtxy0525/Inverse_Dynamics_with_Recursive_Newton_Euler_Algorithm#3]
Hi, I have a few questions.
1. In the mass_center_list, are the elements the position vector of the centroid of the link from the frame at the beginning of the link or the frame at the end of the link?
2. What exactly do you mean by modified DH parameters? Can you please elaborate on the difference between the usual DH parameters and your version?
Any help would be appreciated. Thanks.

**Comment by bhtxy0525** [comment]
Sorry for the late reply.
The position vector of the centroid of the link is described relative to the base coordinate frame.
As for the second question, please refer [here](https://en.wikipedia.org/wiki/Denavit%E2%80%93Hartenberg_parameters) for details.

**Comment by bhtxy0525** [comment]
@MarsGen2032 Sorry for the late reply.
The position vector of the centroid of the link is described relative to the base coordinate frame.
As for the second question, please refer [here](https://en.wikipedia.org/wiki/Denavit%E2%80%93Hartenberg_parameters) for details.

**Comment by MarsGen2032** [comment]
@bhtxy0525 My queries have been cleared now. Thank you for your reply.
